### ISSUE TITLE
build not working on Windows

### ISSUE THREAD

**Issue by mrtnstn** [wadehrarshpreet/react-create-library#1]
I like your project setup, but unfortunately it does not build on Windows. Below is the log output I get when running 'yarn build'. Somehow the build script does not seem to reference the typescript compiler correctly. Would be great if you could help me out.

$ yarn build
yarn run v1.21.1
$ node build-tool/build.js
[generateTypes] '.\\node_modules\\typescript\\bin\\tsc' is not recognized as an internal or external command,
[generateTypes] operable program or batch file.
[umd] 'BUILD_FORMAT' is not recognized as an internal or external command,
[umd] operable program or batch file.
[umd.min] 'BUILD_FORMAT' is not recognized as an internal or external command,
[umd.min] operable program or batch file.
[umd.min] BUILD_FORMAT=umd NODE_ENV=production BUILD_MINIFY=true .\\node_modules\\rollup\\dist\\bin\\rollup --config .\\build-tool\\rollup.config.js --sourcemap exited with code 1
--> Sending SIGTERM to other processes..
[umd] BUILD_FORMAT=umd NODE_ENV=development .\\node_modules\\rollup\\dist\\bin\\rollup --config .\\build-tool\\rollup.config.js --sourcemap exited with code 1
--> Sending SIGTERM to other processes..
[generateTypes] .\\node_modules\\typescript\\bin\\tsc --outDir dist/types --emitDeclarationOnly exited with code 1
--> Sending SIGTERM to other processes..

 [es] .\\node_modules\\@babel\\cli\\bin\\babel.js --presets C:\\git\\mviz\\build-tool\\babelrc.esm.js --out-dir dist/es --ignore src/**/*.test.ts --ignore src/**/*.test.tsx --ignore src/**/*.test.js --ignore src/**/*.test.jsx --extensions .js,.jsx,.es6,.es,.mjs,.ts,.tsx src exited with code 1
--> Sending SIGTERM to other processes..
[esnext] .\\node_modules\\@babel\\cli\\bin\\babel.js --presets C:\\git\\mviz\\build-tool\\babelrc.esm.pure.js --out-dir dist/esnext --ignore src/**/*.test.ts --ignore src/**/*.test.tsx --ignore src/**/*.test.js --ignore src/**/*.test.jsx --extensions .js,.jsx,.es6,.es,.mjs,.ts,.tsx src exited with code 1
--> Sending SIGTERM to other processes..
[cjs] .\\node_modules\\@babel\\cli\\bin\\babel.js --presets C:\\git\\mviz\\build-tool\\babelrc.cjs.js --out-dir dist/cjs --ignore src/**/*.test.ts --ignore src/**/*.test.tsx --ignore src/**/*.test.js --ignore src/**/*.test.jsx --extensions .js,.jsx,.es6,.es,.mjs,.ts,.tsx src exited with code 1
error Command failed with exit code 1.

**Comment by wadehrarshpreet** [comment]
@mrtnstn Issue has been fixed in v1.0.7
